database:
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  default_string_column_size: 191
  reconnect: true
  pool: 1
  username: username
  password: password
  database: database
  host: 127.0.0.1
  port: 3306
